### ISSUE TITLE
Is it possible to use heart shape or other such shapes

### ISSUE THREAD

**Issue by mcwebdev** [tsparticles/angular#40]
I was wondering if shapes were available? The demos I tried do not seem to work. Simple shapes work though.

**Comment by matteobruni** [comment]
All shapes are available in all configurations, if they are not included in the bundle you are using, you have to manually load them. If you have a sample that is not working, please share it so I can see the issue

**Comment by mcwebdev** [comment]
"tsparticles": "^2.9.3",
    "tsparticles-engine": "^2.9.3",

`  id = "tsparticles";
  particlesOptions = {
    fpsLimit: 120,
    particles: {
      color: {
        value: "#a10ea6",
      },
      links: {
        color: "#c619b5",
        distance: 150,
        enable: false,
        opacity: 0.2,
        width: 16,
      },
      move: {
        direction: MoveDirection.bottom,
        enable: true,
        outModes: {
          default: OutMode.bounce,
        },
        random: true,
        speed: 6,
        straight: false,
      },
      shapes: ['circle', 'square', 'triangle', 'polygon', 'star', 'heart', 'edge', 'image'],
      shape: { type: 'heart' },
      number: {
        density: {
          enable: true,
          area: 800,
        },
        value: 80,
      },
      opacity: {
        value: 0.5,
      },
      size: {
        value: { min: 1, max: 5 },
      },
    },
    detectRetina: true,
  };

  particlesLoaded(container: Container): void {
    console.log(container);
  }

  async particlesInit(engine: Engine): Promise<void> {
    console.log(engine);

    // Starting from 1.19.0 you can add custom presets or shape here, using the current tsParticles instance (main)
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(engine);
  }
}`

**Comment by matteobruni** [comment]
`heart` is not included in the `tsparticles` bundle, there's the `tsparticles-shape-heart` package for that.

**Comment by mcwebdev** [comment]
I installed the package, but still do not see the hearts, is there any extra config in the html, or css?

**Comment by matteobruni** [comment]
https://github.com/matteobruni/tsparticles/blob/main/shapes/heart/README.md#usage

Have you called the `loadHeartShape` in your `particlesInit` function? It's async like the `loadFull`, it's better call after that.
