### ISSUE TITLE
Bug:  ng-partciles.component.d.ts

### ISSUE THREAD

**Issue by Webrow** [tsparticles/angular#46]
[ng]   Property '"options"' is incompatible with index signature.
[ng]     Type '{ alias: "options"; required: false; }' is not assignable to type 'string'.

Version 2.10.1 (3.10.1 ng-articles). 

When doing a clean install, there is a typescript error:
![image](https://github.com/tsparticles/angular/assets/3177853/734f254d-e1e7-4c53-815e-7e5604a6ea51)

**Comment by matteobruni** [comment]
Please share some code to replicate the bug

**Comment by CHULMING** [comment]
I'm facing the same issue.

> Please share some code to replicate the bug

```
<ng-particles
  [id]="id"
  [options]="particlesOptions"
  [particlesInit]="particlesInit"
  (particlesLoaded)="particlesLoaded($event)"
></ng-particles>
```
This is a sample code posted on `README`. And All of my codes are same with sample codes. but error occur.
My version : `Angular 15` and `ng-particles 3.11.0`

**Comment by matteobruni** [comment]
`3.11.0` is built with Angular 16 as can be seen here: https://github.com/tsparticles/angular/blob/6ecc7f4b17a30f4930dbedf4715aa329c9fe9139/components/particles/package.json#L81
