### ISSUE TITLE
How to set specific height in Ng-Particles?

### ISSUE THREAD

**Issue by joaoaccaldeira** [tsparticles/angular#63]
The standard css that works for particles.js isn't working for tsparticles. 

I've set the fullScreen option to false in the config:

```
fullScreen: {
    enable: false,
    zIndex: 0
},
```

Calling the ng-particles in the template like this:

```
<ng-particles
    id="tsParticles"
    [options]="tsParticlesConfig"
    [particlesInit]="particlesInit"
></ng-particles>
```

And css this way doesn't work:

```
#tsParticles {
  height: 1000px !important;
}

```
For some reason the canvas that is inside the ng-particles component gets set with an attribute of height "148".

![tsz](https://github.com/tsparticles/angular/assets/6305957/b413e112-d0be-40bf-ac1f-782192f27625)

Any help on this or any working example where the animations only work in the first 900px for example.

**Comment by matteobruni** [comment]
https://codesandbox.io/p/sandbox/great-galois-w6gr25?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A21%2C6

```
options = {
    fullScreen: {
      enable: false,
    },
    background: {
      color: '#f00',
    },
    style: {
      height: '1000px',
    },
  };
```

**Comment by joaoaccaldeira** [comment]
> https://codesandbox.io/p/sandbox/great-galois-w6gr25?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A21%2C6
> 
> ```
> options = {
>     fullScreen: {
>       enable: false,
>     },
>     background: {
>       color: '#f00',
>     },
>     style: {
>       height: '1000px',
>     },
>   };
> ```

Oh wow, that's exactly what I wanted, thanks a lot for the quick and clear reply!
